//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class basic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basic()
        {
            this.educations = new HashSet<education>();
            this.skills = new HashSet<skill>();
            this.works = new HashSet<work>();
            this.leaves = new HashSet<leave>();
            this.raises = new HashSet<raise>();
        }
    
        public int empid { get; set; }
        public string empname { get; set; }
        public string emptype { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateofjoin { get; set; }
        public string gender { get; set; }
        [DisplayName("Upload Photo")]
        public string emp_photo_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<education> educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work> works { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave> leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raise> raises { get; set; }
    }
}
