//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public string Tenth_percentage { get; set; }
        public Nullable<int> Tenth_yop { get; set; }
        public string Twelfth_percentage { get; set; }
        public Nullable<int> Twelfth_yop { get; set; }
        public string UG_percentage { get; set; }
        public Nullable<int> UG_yop { get; set; }
        public string PG_percentage { get; set; }
        public string PG_yop { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
