//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raise
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public string curloc { get; set; }
        public string precontim { get; set; }
        public string shortdes { get; set; }
        public string des { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
