//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public string primary_skills { get; set; }
        public string other_skills { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
